version: "3"
services:
  maria_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: docker
    ports:
      - "3306:3306"
    volumes:
      - ./db_files:/var/lib/mysql
  httpd:
    image: jrma/php56:cron
    links:
      - maria_db:db
    ports:
      - "80:80"
    volumes:
      - "./public_html:/var/www/html"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - maria_db:db
    ports:
      - "8181:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: docker
