httpd:
  image: jrma/php56:v1
  links:
    - maria_db:db
  ports:
    - 80:80
  volumes:
    - ./public_html:/var/www/html
maria_db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: docker
  ports:
    - 3306:3306
  expose:
    - "3306"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - maria_db:db
  ports:
    - 8181:80
  environment:
    PMA_USER: root
    PMA_PASSWORD: docker
